Bloggie/Bloggie.Web/Pages/Admin/Blogs/Add.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Server.IIS.Core;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    [Authorize(Roles ="Admin")]
    public class AddModel : PageModel
    {
        public String errorMessage = "";
        private IBlogPostRepository blogPostRepository;

        [BindProperty]
        [Required]
        public string Tags { get; set; }
        [BindProperty]
        public AddBlogPost AddBlogPostRequest { get; set; }
        [BindProperty]
        public IFormFile FeaturedImage { get; set; }
        public AddModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            ValidateAddBlogPost();
            if (ModelState.IsValid)
            {
                try
                {
                    if (AddBlogPostRequest.Heading.Length != 0 || AddBlogPostRequest.PageTitle.Length != 0 || AddBlogPostRequest.Content.Length != 0
                        || AddBlogPostRequest.ShortDescription.Length != 0 || AddBlogPostRequest.FeaturedImageUrl.Length != 0 || AddBlogPostRequest.UrlHandle.Length != 0
                         || AddBlogPostRequest.Author.Length != 0)
                    {
                        var time = AddBlogPostRequest.PublishDate;
                        if (time == null)
                        {
                            time = DateTime.Now;
                        }
                        var blogPost = new BlogPost
                        {
                            Heading = AddBlogPostRequest.Heading,
                            PageTitle = AddBlogPostRequest.PageTitle,
                            Content = AddBlogPostRequest.Content,
                            ShortDescription = AddBlogPostRequest.ShortDescription,
                            FeaturedImageUrl = AddBlogPostRequest.FeaturedImageUrl,
                            UrlHandle = AddBlogPostRequest.UrlHandle,
                            PublishDate = (DateTime)time,
                            Author = AddBlogPostRequest.Author,
                            Visible = AddBlogPostRequest.Visible,
                            Tags = new List<Tag>(Tags.Split(',').Select(x => new Tag() { Name = x.Trim() }))

                        };

                        await blogPostRepository.AddAsync(blogPost);

                        var notification = new Notification
                        {
                            Type = enums.NotificationType.Success,
                            Message = "New Blog Created!"
                        };
                        TempData["Notification"] = JsonSerializer.Serialize(notification);
                    }
                }
           
           
            catch (Exception)
            {

                errorMessage = "All the fields are required";
                return Page();
            }
                
                    
            return Redirect("/Admin/Blogs/List");
        }
            return Page();
        }

        //custom validation
        private void ValidateAddBlogPost()
        {
            if(AddBlogPostRequest.PublishDate.Date < DateTime.Now.Date)
            {
                ModelState.AddModelError("AddBlogPostRequest.PublishDate",
                    $"{nameof(AddBlogPostRequest.PublishDate)} can only be today's date or future date.");
            }
        }
    }
}
            
            

        
    

Bloggie/Bloggie.Web/Pages/Admin/Blogs/Edit.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;
        public EditModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }

        [BindProperty]
        public IFormFile? FeaturedImage { get; set; }

        [BindProperty]
        [Required]
        public string Tags { get; set; }

        [BindProperty]
        public EditBlogPostRequest BlogPost { get; set; }
        
        public async Task OnGet(Guid id)
        {
           var blogPostDomainModel =  await blogPostRepository.GetAsync(id);
            if( blogPostDomainModel != null && blogPostDomainModel.Tags != null)
            {
                BlogPost = new EditBlogPostRequest
                {
                    Id = blogPostDomainModel.Id,
                    Heading = blogPostDomainModel.Heading,
                    PageTitle = blogPostDomainModel.PageTitle,
                    Content = blogPostDomainModel.Content,
                    ShortDescription = blogPostDomainModel.ShortDescription,
                    FeaturedImageUrl = blogPostDomainModel.FeaturedImageUrl,
                    UrlHandle = blogPostDomainModel.UrlHandle,
                    PublishDate = blogPostDomainModel.PublishDate,
                    Author = blogPostDomainModel.Author,
                    Visible = blogPostDomainModel.Visible

                };
                Tags = String.Join(',', blogPostDomainModel.Tags.Select(x => x.Name));
            }
            
        }


        public async Task<IActionResult> OnPostEdit()
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var blogPostDomainModel = new BlogPost
                    {
                        Id = BlogPost.Id,
                        Heading = BlogPost.Heading,
                        PageTitle = BlogPost.PageTitle,
                        Content = BlogPost.Content,
                        ShortDescription = BlogPost.ShortDescription,
                        FeaturedImageUrl = BlogPost.FeaturedImageUrl,
                        UrlHandle = BlogPost.UrlHandle,
                        PublishDate = BlogPost.PublishDate,
                        Author = BlogPost.Author,
                        Visible = BlogPost.Visible,
                        Tags = new List<Tag>(Tags.Split(',').Select(x => new Tag() { Name = x.Trim() }))
                    };

                    await blogPostRepository.UpdateAsync(blogPostDomainModel);

                    var notification = new Notification
                    {
                        Type = enums.NotificationType.Success,
                        Message = "Record updated successfully!"
                    };
                    TempData["Notification"] = JsonSerializer.Serialize(notification);

                }
                catch (Exception ex)
                {
                    ViewData["Notification"] = new Notification
                    {
                        Message = "There was an error",
                        Type = enums.NotificationType.Error
                    };
                    return Page();
                }

                return RedirectToPage("/Admin/Blogs/List");
            }
            return Page();

            
            
        }

        
        public async Task<IActionResult> OnPostDelete()
        {
           var deleted =  await blogPostRepository.DeleteAsync(BlogPost.Id);
            if (deleted)
            {
                var notification = new Notification
                {
                    Type = enums.NotificationType.Success,
                    Message = "the blogpost has been deleted!"
                };
                TempData["Notification"] = JsonSerializer.Serialize(notification);

                return RedirectToPage("/Admin/Blogs/List");
            }
            
            return Page();
        }
    }
}

Bloggie/Bloggie.Web/Pages/Admin/Blogs/List.cshtml.cs
using Bloggie.Web.Data;
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Bloggie.Web.Pages.Admin.Blogs
{
    [Authorize(Roles = "Admin")]
    public class ListModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;

        public List<BlogPost> BlogPosts { get; set; }
        [BindProperty]
        public BlogPost BlogPost { get; set; }
        public ListModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }
        public async Task OnGet()
        {
            var notificationJson = (string)TempData["Notification"];
            if (notificationJson != null)
            {
                ViewData["Notification"] = JsonSerializer.Deserialize<Notification>(notificationJson);
            }

           BlogPosts= (await blogPostRepository.GetAllAsync())?.ToList();
        }
        public async Task<IActionResult> OnPostDelete()
        {

            var deleted = await blogPostRepository.DeleteAsync(BlogPost.Id);
            if (deleted)
            {
                var notification = new Notification
                {
                    Message = "The blogpost has been deleted!",
                    Type = enums.NotificationType.Success,
                };
                TempData["Notification"] = JsonSerializer.Serialize(notification);
                return RedirectToPage("/Admin/Blogs/List");
            }
            return Page();
        }
       

}
}

Bloggie/Bloggie.Web/Pages/Blog/BlogDetails.cshtml.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Models.ViewModels;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace Bloggie.Web.Pages.Blog
{
    public class BlogDetailsModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;
        private readonly IBlogPostLikeRepository blogPostLikeRepository;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IBlogPostCommentRepository blogPostCommentRepository;

        public BlogPost BlogPost { get; set; }
        public List<BlogComment> Comments { get; set; }
        public int TotalLikes { get; set; }
        public bool Liked { get; set; }
        [BindProperty]
        public Guid BlogPostId { get; set; }
        [BindProperty]
        [Required]
        [MinLength(1)]
        [MaxLength(200)]
        public string CommentDescription { get; set; }

        public BlogDetailsModel(IBlogPostRepository blogPostRepository,
            IBlogPostLikeRepository blogPostLikeRepository,
            SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager,IBlogPostCommentRepository blogPostCommentRepository
            )
        {
            this.blogPostRepository = blogPostRepository;
            this.blogPostLikeRepository = blogPostLikeRepository;
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.blogPostCommentRepository = blogPostCommentRepository;
        }


        public async Task<IActionResult> OnGet(string urlHandle)
        {
            await GetBlog(urlHandle);
            return Page();
        }

        public async Task<IActionResult> OnPost(string urlHandle)
        {
            if (ModelState.IsValid)
            {

                if (signInManager.IsSignedIn(User) && !string.IsNullOrWhiteSpace(CommentDescription))
                {
                    var userId = userManager.GetUserId(User);
                    var comment = new BlogPostComment()
                    {
                        BlogPostId = BlogPostId,
                        Description = CommentDescription,
                        DateAdded = DateTime.Now,
                        UserId = Guid.Parse(userId)
                    };

                    await blogPostCommentRepository.AddAsync(comment);
                }
                return RedirectToPage("/blog/blogdetails", new { urlHandle = urlHandle });
            }
            await GetBlog(urlHandle);
            return Page();
        }

        private async Task GetComments()
        {
            var blogPostComments = await blogPostCommentRepository.GetAllAsync(BlogPost.Id);
            var blogCommentsViewModel = new List<BlogComment>();
            foreach (var blogPostComment in blogPostComments)
            {
                blogCommentsViewModel.Add(new BlogComment()
                {
                    DateAdded = blogPostComment.DateAdded,
                    Description = blogPostComment.Description,
                    UserName = (await userManager.FindByIdAsync(blogPostComment.UserId.ToString())).UserName
                });
            }

            Comments = blogCommentsViewModel;
        }
        private async Task GetBlog(string urlHandle)
        {
            BlogPost = await blogPostRepository.GetAsync(urlHandle);
            if (BlogPost != null)
            {
                BlogPostId = BlogPost.Id;
                if (signInManager.IsSignedIn(User))
                {
                    var likes = await blogPostLikeRepository.GetLikesForBlog(BlogPost.Id);
                    var userId = userManager.GetUserId(User);

                    Liked = likes.Any(x => x.UserId == Guid.Parse(userId));

                    await GetComments();
                }
                TotalLikes = await blogPostLikeRepository.GetTotalLikesForBlog(BlogPost.Id);
            }
        }
    }
}

Bloggie/Bloggie.Web/Pages/Blog/Details.cshtml.cs
using Bloggie.Web.Models.Domain;
using Bloggie.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bloggie.Web.Pages.Blog
{
    public class DetailsModel : PageModel
    {
        private readonly IBlogPostRepository blogPostRepository;
        [BindProperty]
        public BlogPost BlogPost { get; set; }
        public DetailsModel(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }


        public async Task<IActionResult> OnGet(string urlHandle)
        {
           BlogPost =  await blogPostRepository.GetAsync(urlHandle);

            return Page();
        }

        public async Task<IActionResult> OnPost(string Name)
        {
            BlogPost = await blogPostRepository.GetAsync(Name);
            return RedirectToPage("/blog/blogtags/Name");
        }
    }
}

Bloggie/Bloggie.Web/Pages/Admin/Blogs/Add.cshtml
@page
@model Bloggie.Web.Pages.Admin.Blogs.AddModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
<h1> Add Blog Post</h1> 

    </div>
</div>
@*NOTIFICATION BLOCK*@
@if (Model.errorMessage.Length > 0)
{
    <div class="container alert alert-warning alert-dismissible fade show" role="alert">
        <strong>@Model.errorMessage</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
}

@*FORM BLOCK*@

        <form method="post" enctype="multipart/form-data">
        <div class="container mb-3">
                <label for="heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="AddBlogPostRequest.Heading" required/>
                <span class="text-danger" asp-validation-for="AddBlogPostRequest.Heading"></span>
        </div>
        <div class="container mb-3">
            <label for="pageTitle" class="form-label">Page Title</label>
            <input type="text" class="form-control" id="pageTitle" asp-for="AddBlogPostRequest.PageTitle"required />
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.PageTitle"></span>
        </div>
        <div class="container mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" asp-for="AddBlogPostRequest.Content"required></textarea>
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.Content"></span>
        </div>
        <div class="container mb-3">
            <label for="featuredImageUpload" class="form-label">Featured Image Upload</label>
            <input type="file" id="featuredImageUpload" asp-for="FeaturedImage" />
            <img src="" id="featuredImageDisplay" style="display:none; width:300px;" />
        </div>

        <div class="container mb-3">
            <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
            <input type="text" class="form-control" id="featuredImageUrl" asp-for="AddBlogPostRequest.FeaturedImageUrl" required/>
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.FeaturedImageUrl"></span>
        </div>
        <div class="container mb-3">
            <label for="shortDescription" class="form-label">Short Description</label>
            <input type="text" class="form-control" id="shortDescription" asp-for="AddBlogPostRequest.ShortDescription" required/>
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.ShortDescription"></span>
        </div>
        <div class="container mb-3">
            <label for="urlHandle" class="form-label">Url Handle</label>
            <input type="text" class="form-control" id="urlHandle" asp-for="AddBlogPostRequest.UrlHandle" required/>
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.UrlHandle"></span>
        </div>
        <div class="container mb-3">
            <label for="publishedDate" class="form-label">Published date</label>
            <input type="date" class="form-control" id="publishedDate" asp-for="AddBlogPostRequest.PublishDate"required />
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.PublishDate"></span>
        </div>
        <div class="container mb-3">
            <label for="author" class="form-label">Author</label>
            <input type="text" class="form-control" id="author" asp-for="AddBlogPostRequest.Author"required />
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.Author"></span>
        </div>

        <div class=" container mb-3 ">
            <label for="" class="form-label">Tags (comma seperated)</label>
            <input type="" class="form-control" required id="Tags" asp-for="Tags" />
            <span class="text-danger" asp-validation-for="Tags"></span>
        </div>
        <div class="container mb-3 mt-3">
            <input class="form-check-input" required type="checkbox" id="isVisible" asp-for="AddBlogPostRequest.Visible" />
            <span class="text-danger" asp-validation-for="AddBlogPostRequest.Visible"></span>
            <label class="form-check-label" for="isVisible">
                Is Visible
            </label>
        </div>
            <div class="container mb-3 mt-3">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>


@section Scripts {
    <script>
        var editor = new FroalaEditor("#content",{
            imageUploadURL: '/api/images'
        });

        const featuredImageUploadelement = document.getElementById("featuredImageUpload");
        const featuredImageUrl = document.getElementById("featuredImageUrl");
        const featuredImageDisplay = document.getElementById("featuredImageDisplay");

        async function uploadFeaturedImage(e) {

            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            debugger;
            await fetch('/api/images',{
                method : 'POST',
                headers : {
                    'Accept' : '*/*',
                },
                    body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageUrl.value = result.link;
                    featuredImageDisplay.style.display = 'block';
                    featuredImageDisplay.src = result.link;
                })
            };

        featuredImageUploadelement.addEventListener('change', uploadFeaturedImage);
    </script>
}


@*
    <form>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

*@

Bloggie/Bloggie.Web/Pages/Admin/Blogs/Edit.cshtml
@page "{id:Guid}"

@model Bloggie.Web.Pages.Admin.Blogs.EditModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Edit Blog Post</h1>

    </div>

</div>
<partial name="_Notification"></partial>

@if (Model.BlogPost != null){
    <div>
        <form method="post">
            <div class="container mb-3">
                <label for="id" class="form-label">Id</label>
                <input type="text" class="form-control" id="id" asp-for="BlogPost.Id" readonly>
                <span class="text-danger" asp-validation-for="BlogPost.Id"></span>
            </div>
            <div class="container mb-3">
                <label for="heading" class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="BlogPost.Heading" required>
                <span class="text-danger" asp-validation-for="BlogPost.Heading"></span>

            </div>
            <div class="container mb-3">
                <label for="pageTitle" class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pageTitle" asp-for="BlogPost.PageTitle" required>
                <span class="text-danger" asp-validation-for="BlogPost.PageTitle"></span>

            </div>
            <div class="container mb-3">
                <label for="content" class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="BlogPost.Content" required></textarea>
                <span class="text-danger" asp-validation-for="BlogPost.Content"></span>

            </div>
            <div class="container mb-3">
                <label for="featuredImageUpload" class="form-label">Featured Image Upload</label>
                <input type="file" id="featuredImageUpload" asp-for="FeaturedImage" />

                @if (Model.BlogPost.FeaturedImageUrl != null)
                {
                    <img src="@Model.BlogPost.FeaturedImageUrl" id="featuredImageDisplay" style="display:block; width:300px;" />
                }
                else
                {
                    <img src="" id="featuredImageDisplay" style="display:none; width:300px;" />
                }
            </div>
            <div class="container mb-3">
                <label for="featuredImageUrl" class="form-label">Featured Image Url</label>
                <input type="text" class="form-control" id="featuredImageUrl" asp-for="BlogPost.FeaturedImageUrl" required>
                <span class="text-danger" asp-validation-for="BlogPost.FeaturedImageUrl"></span>

            </div>
            <div class="container mb-3">
                <label for="shortDescription" class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortDescription" asp-for="BlogPost.ShortDescription" required>
                <span class="text-danger" asp-validation-for="BlogPost.ShortDescription"></span>

            </div>
            <div class="container mb-3">
                <label for="urlHandle" class="form-label">Url Handle</label>
                <input type="text" class="form-control" id="urlHandle" asp-for="BlogPost.UrlHandle" required>
                <span class="text-danger" asp-validation-for="BlogPost.UrlHandle"></span >

            </div>
            <div class="container mb-3">
                <label for="publishedDate" class="form-label">Published date</label>
                <input type="date" class="form-control" id="publichsedDate" asp-for="BlogPost.PublishDate"required>
                <span class="text-danger" asp-validation-for="BlogPost.PublishDate"></span>

            </div>
            <div class="container mb-3">
                <label for="author" class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="BlogPost.Author">
                <span class="text-danger" asp-validation-for="BlogPost.Author"></span>

            </div>

            <div class="container mb-3">
                <label class="form-label">Tags (comma seperated)</label>
                <input type="text" class="form-control" id="tags" asp-for="Tags" />
                <span class="text-danger" asp-validation-for="Tags"></span>

            </div>

            <div class="container mb-3 mt-3">
                <input class="form-check-input" type="checkbox" id="isVisible" asp-for="BlogPost.Visible">
                <label class="form-check-label" for="isVisible">
                    Is Visible
                </label>
            </div>
            <div class="container mb-3 mt-3 ">
                <button class="btn btn-primary " type="submit" asp-page-handler="Edit">Submit</button>

                <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
            </div>
        </form>

    </div>
}
else {
    <div class="container">
        <p>Blog Post not found</p>
    </div>
}

@section Scripts {
    <script>
        var editor = new FroalaEditor("#content", {
            imageUploadURL: '/api/images'
        });

        const featuredImageUploadelement = document.getElementById("featuredImageUpload");
        const featuredImageUrl = document.getElementById("featuredImageUrl");
        const featuredImageDisplay = document.getElementById("featuredImageDisplay");

        async function uploadFeaturedImage(e) {

            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageUrl.value = result.link;
                    featuredImageDisplay.style.display = 'block';
                    featuredImageDisplay.src = result.link;
                })
        };

        featuredImageUploadelement.addEventListener('change', uploadFeaturedImage);
    </script>

}

Bloggie/Bloggie.Web/Pages/Admin/Blogs/List.cshtml
@page 
@model Bloggie.Web.Pages.Admin.Blogs.ListModel
@{
}


<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1> Blog Posts</h1>
    </div>
</div>
<partial name="_Notification"></partial>
@if (Model.BlogPosts != null && Model.BlogPosts.Any() ){
    
   
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Heading</td>
                    <td></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.BlogPosts)
                {
                    <form method="post">
                    <tr>
                        <td>@item.Id</td>
                        <input type="text" class="form-control" name="id" value="@item.Id" hidden>
                        <td>@item.Heading</td>
                        <td>@item.PublishDate</td>
                        <td>
                            <a href="/Admin/Blogs/Edit/@item.Id" class="btn btn-primary">Edit</a>
                        </td>
                        <td>

                            <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
                        </td>

                    </tr>
                    </form>

                }
            </tbody>
        </table>
    </div>
}else
{
    <div class="container">
        <p>No Blog posts were found!</p>
    </div>
}